In [1]:
import datetime

# scientific python add-ons
import numpy as np
import pandas as pd

# plotting stuff
# first line makes the plots appear in the notebook
%matplotlib inline 
import matplotlib.pyplot as plt
# seaborn makes your plots look better
try:
    import seaborn as sns
    sns.set(rc={"figure.figsize": (16, 8)})
except ImportError:
    print('We suggest you install seaborn using conda or pip and rerun this cell')

# finally, we import the pvlib library
import pvlib
from pvlib.location import Location

##Set Location and Date

In [2]:
Ein = Location(51.4098395,5.455063, 'Europe/Amsterdam', 20, 'Eindhoven')
times = pd.date_range(start=datetime.datetime(2015,5,23 ), end=datetime.datetime(2015,5,24 ), freq='1Min')
times_loc = times.tz_localize(Ein.pytz)
print(Ein)

Eindhoven: latitude=51.4098395, longitude=5.455063, tz=Europe/Amsterdam, altitude=20

##Build Dataframe

In [3]:
spaout = pvlib.solarposition.spa_python(times_loc, Ein)[0:1440]
spaout

,apparent_elevation,apparent_zenith,azimuth,elevation,equation_of_time,zenith
2015-05-23 00:00:00+02:00,-15.185511,105.185511,337.019482,-15.185511,3.332825,105.185511
2015-05-23 00:01:00+02:00,-15.245963,105.245963,337.253987,-15.245963,3.332771,105.245963
2015-05-23 00:02:00+02:00,-15.305826,105.305826,337.488722,-15.305826,3.332716,105.305826
2015-05-23 00:03:00+02:00,-15.365098,105.365098,337.723683,-15.365098,3.332662,105.365098
2015-05-23 00:04:00+02:00,-15.423778,105.423778,337.958871,-15.423778,3.332607,105.423778
2015-05-23 00:05:00+02:00,-15.481865,105.481865,338.194283,-15.481865,3.332553,105.481865
2015-05-23 00:06:00+02:00,-15.539356,105.539356,338.429918,-15.539356,3.332498,105.539356
2015-05-23 00:07:00+02:00,-15.596251,105.596251,338.665774,-15.596251,3.332444,105.596251
2015-05-23 00:08:00+02:00,-15.652547,105.652547,338.901850,-15.652547,3.332389,105.652547
2015-05-23 00:09:00+02:00,-15.708244,105.708244,339.138143,-15.708244,3.332334,105.708244
2015-05-23 00:10:00+02:00,-15.763339,105.763339,339.374653,-15.763339,3.332280,105.763339
2015-05-23 00:11:00+02:00,-15.817832,105.817832,339.611377,-15.817832,3.332225,105.817832
2015-05-23 00:12:00+02:00,-15.871721,105.871721,339.848313,-15.871721,3.332171,105.871721
2015-05-23 00:13:00+02:00,-15.925003,105.925003,340.085460,-15.925003,3.332116,105.925003
2015-05-23 00:14:00+02:00,-15.977679,105.977679,340.322816,-15.977679,3.332062,105.977679
2015-05-23 00:15:00+02:00,-16.029746,106.029746,340.560380,-16.029746,3.332007,106.029746
2015-05-23 00:16:00+02:00,-16.081203,106.081203,340.798148,-16.081203,3.331952,106.081203
2015-05-23 00:17:00+02:00,-16.132049,106.132049,341.036120,-16.132049,3.331898,106.132049
2015-05-23 00:18:00+02:00,-16.182282,106.182282,341.274294,-16.182282,3.331843,106.182282
2015-05-23 00:19:00+02:00,-16.231900,106.231900,341.512667,-16.231900,3.331789,106.231900
2015-05-23 00:20:00+02:00,-16.280904,106.280904,341.751238,-16.280904,3.331734,106.280904
2015-05-23 00:21:00+02:00,-16.329290,106.329290,341.990004,-16.329290,3.331679,106.329290
2015-05-23 00:22:00+02:00,-16.377058,106.377058,342.228964,-16.377058,3.331625,106.377058
2015-05-23 00:23:00+02:00,-16.424206,106.424206,342.468115,-16.424206,3.331570,106.424206
2015-05-23 00:24:00+02:00,-16.470733,106.470733,342.707456,-16.470733,3.331516,106.470733
2015-05-23 00:25:00+02:00,-16.516639,106.516639,342.946985,-16.516639,3.331461,106.516639
2015-05-23 00:26:00+02:00,-16.561920,106.561920,343.186699,-16.561920,3.331406,106.561920
2015-05-23 00:27:00+02:00,-16.606577,106.606577,343.426596,-16.606577,3.331352,106.606577
2015-05-23 00:28:00+02:00,-16.650608,106.650608,343.666674,-16.650608,3.331297,106.650608
2015-05-23 00:29:00+02:00,-16.694012,106.694012,343.906931,-16.694012,3.331242,106.694012
...,...,...,...,...,...,...
2015-05-23 23:30:00+02:00,-12.918765,102.918765,330.144201,-12.918765,3.251936,102.918765
2015-05-23 23:31:00+02:00,-12.995996,102.995996,330.370785,-12.995996,3.251876,102.995996
2015-05-23 23:32:00+02:00,-13.072691,103.072691,330.597631,-13.072691,3.251816,103.072691
2015-05-23 23:33:00+02:00,-13.148848,103.148848,330.824738,-13.148848,3.251756,103.148848
2015-05-23 23:34:00+02:00,-13.224464,103.224464,331.052105,-13.224464,3.251695,103.224464
2015-05-23 23:35:00+02:00,-13.299539,103.299539,331.279732,-13.299539,3.251635,103.299539
2015-05-23 23:36:00+02:00,-13.374070,103.374070,331.507617,-13.374070,3.251575,103.374070
2015-05-23 23:37:00+02:00,-13.448055,103.448055,331.735761,-13.448055,3.251515,103.448055
2015-05-23 23:38:00+02:00,-13.521493,103.521493,331.964160,-13.521493,3.251455,103.521493
2015-05-23 23:39:00+02:00,-13.594382,103.594382,332.192816,-13.594382,3.251394,103.594382
2015-05-23 23:40:00+02:00,-13.666721,103.666721,332.421727,-13.666721,3.251334,103.666721
2015-05-23 23:41:00+02:00,-13.738507,103.738507,332.650892,-13.738507,3.251274,103.738507
2015-05-23 23:42:00+02:00,-13.809738,103.809738,332.880309,-13.809738,3.251214,103.809738
2015-05-23 23:43:00+02:00,-13.880413,103.880413,333.109979,-13.880413,3.251154,103.880413
2015-05-23 23:44:00+02:00,-13.950531,103.950531,333.339899,-13.950531,3.251093,103.950531
2015-05-23 23:45:00+02:00,-14.020089,104.020089,333.570069,-14.020089,3.251033,104.020089
2015-05-23 23:46:00+02:00,-14.089085,104.089085,333.800488,-14.089085,3.250973,104.089085
2015-05-23 23:47:00+02:00,-14.157519,104.157519,334.031155,-14.157519,3.250913,104.157519
2015-05-23 23:48:00+02:00,-14.225387,104.225387,334.262067,-14.225387,3.250852,104.225387
2015-05-23 23:49:00+02:00,-14.292690,104.292690,334.493225,-14.292690,3.250792,104.292690
2015-05-23 23:50:00+02:00,-14.359424,104.359424,334.724628,-14.359424,3.250732,104.359424
2015-05-23 23:51:00+02:00,-14.425588,104.425588,334.956272,-14.425588,3.250671,104.425588
2015-05-23 23:52:00+02:00,-14.491181,104.491181,335.188159,-14.491181,3.250611,104.491181
2015-05-23 23:53:00+02:00,-14.556200,104.556200,335.420285,-14.556200,3.250551,104.556200
2015-05-23 23:54:00+02:00,-14.620645,104.620645,335.652651,-14.620645,3.250491,104.620645
2015-05-23 23:55:00+02:00,-14.684513,104.684513,335.885254,-14.684513,3.250430,104.684513
2015-05-23 23:56:00+02:00,-14.747803,104.747803,336.118093,-14.747803,3.250370,104.747803
2015-05-23 23:57:00+02:00,-14.810513,104.810513,336.351167,-14.810513,3.250310,104.810513
2015-05-23 23:58:00+02:00,-14.872642,104.872642,336.584475,-14.872642,3.250250,104.872642
2015-05-23 23:59:00+02:00,-14.934188,104.934188,336.818015,-14.934188,3.250189,104.934188

##Passing Values to table

In [4]:
import sqlite3
import pandas as pd
from pandas.io import sql

In [5]:
time=spaout.index
elevation=spaout['elevation']

##Create new table and connect

In [6]:
conn = sqlite3.connect('/Users/vlasis/Desktop/mytable1.db')
df = pd.DataFrame({'Elevation':elevation})

In [20]:
a=df
cnx = sqlite3.connect('/Users/vlasis/Desktop/mytable1.db')
sql.write_frame(a, name='sa', con=cnx)

#Read from table

In [24]:
p2 = sql.read_frame('select * from sa', cnx)
p2

      Elevation
0    -15.185511
1    -15.245963
2    -15.305826
3    -15.365098
4    -15.423778
5    -15.481865
6    -15.539356
7    -15.596251
8    -15.652547
9    -15.708244
10   -15.763339
11   -15.817832
12   -15.871721
13   -15.925003
14   -15.977679
15   -16.029746
16   -16.081203
17   -16.132049
18   -16.182282
19   -16.231900
20   -16.280904
21   -16.329290
22   -16.377058
23   -16.424206
24   -16.470733
25   -16.516639
26   -16.561920
27   -16.606577
28   -16.650608
29   -16.694012
...         ...
1410 -12.918765
1411 -12.995996
1412 -13.072691
1413 -13.148848
1414 -13.224464
1415 -13.299539
1416 -13.374070
1417 -13.448055
1418 -13.521493
1419 -13.594382
1420 -13.666721
1421 -13.738507
1422 -13.809738
1423 -13.880413
1424 -13.950531
1425 -14.020089
1426 -14.089085
1427 -14.157519
1428 -14.225387
1429 -14.292690
1430 -14.359424
1431 -14.425588
1432 -14.491181
1433 -14.556200
1434 -14.620645
1435 -14.684513
1436 -14.747803
1437 -14.810513
1438 -14.872642
1439 -14.934188

[1440 rows x 1 columns]